Saving files so I can attempt to resolve gh-pages push conflict.
I receive the following error when pushing the subtree gh-pages:

gifford@Kevins-MacBook-Pro-2 /Users/gifford/GitHub/book> git subtree push --prefix _book origin gh-pages
git push using:  origin gh-pages
-n 1/      28 (0)
-n 2/      28 (1)
-n 3/      28 (2)
-n 4/      28 (3)
-n 5/      28 (4)
-n 6/      28 (5)
-n 7/      28 (6)
-n 8/      28 (7)
-n 9/      28 (8)
-n 10/      28 (9)
-n 11/      28 (10)
-n 12/      28 (11)
-n 13/      28 (12)
-n 14/      28 (13)
-n 15/      28 (14)
-n 16/      28 (15)
-n 17/      28 (16)
-n 18/      28 (17)
-n 19/      28 (18)
-n 20/      28 (19)
-n 21/      28 (20)
-n 22/      28 (21)
-n 23/      28 (22)
-n 24/      28 (23)
-n 25/      28 (24)
-n 26/      28 (25)
-n 27/      28 (26)
-n 28/      28 (27)
To https://github.com/KevinKGifford/book.git
 ! [rejected]        2af8864cfa3d4102803d6b3f471409828c8b99a9 -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/KevinKGifford/book.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
gifford@Kevins-MacBook-Pro-2 /Users/gifford/GitHub/book> git push origin master
Counting objects: 83, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (83/83), done.
Writing objects: 100% (83/83), 43.91 KiB | 0 bytes/s, done.
Total 83 (delta 64), reused 0 (delta 0)
To https://github.com/KevinKGifford/book.git
   94c32ad..efb86fb  master -> master
gifford@Kevins-MacBook-Pro-2 /Users/gifford/GitHub/book>